### ISSUE TITLE
mdsilo deb file doesn't work in Ubuntu 22.04

### ISSUE THREAD

**Issue by amiyatulu** [mdSilo/mdSilo-app#364]
Starting mdsilo 0.5.3 in 22.04 loads with blank white screen.

It gives error:
Unsupported modifier, resource creation failed.
XXX: resource creation failed

![Screenshot from 2023-02-08 11-58-17](https://user-images.githubusercontent.com/2051004/217452328-6ebd8431-e5cf-4316-b58f-208d73b60b2c.png)

**Comment by danloh** [comment]
It works well on my Ubuntu 22.04.1 LTS.  Would you like providing more context?

**Comment by amiyatulu** [comment]
I don't know why its happening in my system.

**Comment by danloh** [comment]
Did some search, it maybe due to: 
- sth weird on Ubuntu 22.04 
- graphic driver issue

**Comment by danloh** [comment]
I will close this issue, I guess there is nothing can do from mdsilo side
