### ISSUE TITLE
Using the 'Check for Updates' button (About page) sends you to wrong repository

### ISSUE THREAD

**Issue by aci-d** [mdSilo/mdSilo-app#398]
**Describe the bug**
In the Desktop app, using the 'Check for Updates' button (About page) sends you to repository `https://github.com/mdSilo/mdSilo/releases`. 
This should be fine but the issue is that currently the `https://github.com/mdSilo/mdSilo/releases` repository shows 0.5.3 as the latest version, whereas the `https://github.com/mdSilo/mdSilo-app/releases` has 0.5.4 as the latest version. So I didn't have the latest version of the Desktop app and didn't know about it.

**To Reproduce**
Desktop App Version 0.5.3 on Linux
1. mdSilo main menu > About
2. Click the 'Check for Updates button'
3. Observe that you are sent to `https://github.com/mdSilo/mdSilo/releases`. The latest version is apparently 0.5.3
Note I only detected this as an issue by coincidentally seeing that version 0.5.4 was the latest version on `https://mdsilo.com/`

**Expected behavior**
I'd expect the two repositories to be either
A) synced in github so it doesn't matter, or else
B) the Desktop app should send you to the Desktop app repository so you always have the latest Desktop app version.

**Screenshots**
None.

**Desktop (please complete the following information):**

- Linux Mint 21.1
- mdSilo version 0.5.3

**Additional context**
None.

**Comment by danloh** [comment]
Thanks, will fix it
