### ISSUE TITLE
Editing WYSIWYG mode lags significantly for large files

### ISSUE THREAD

**Issue by aci-d** [mdSilo/mdSilo-app#399]
**Is your feature request related to a problem? Please describe.**
I noticed that editing WYSIWYG mode lags significantly for large files, even if they have no styling (plain text).
e.g.
I have a file which currently has more than 7000 lines (yes, pretty extreme case). It takes about 10+ seconds to load (tolerable).
However, once loaded, adding a new line in WYSIWYG mode takes another 10+ seconds. 
I find this a bit strange since the file is already loaded... what is it thinking about? Is it refreshing the whole file? Does it have to?

**Describe the solution you'd like**
I think WYSIWIG mode should be as responsive as possible as it is the default mode. I feel like this might be possible if the rendering doesn't refresh the whole document (not sure if that's what's being done but I guess so?)

A workaround could include making mdSilo remember the mode last used between shutdowns, or having a default setting for startup mode.

**Describe alternatives you've considered**
- Using markdown mode for this kind of operation is much more tolerable and I'll do this for now
- My text editor is fine with large files so I'd probably not do this type of operation in mdSilo in future

**Additional context**
A 4000-line file is quite tolerable - takes about 3 seconds to open and 3 seconds to add new lines, etc. but still keen to cut down that editing time.
In general I would also say this is pretty low priority to address right now but just something I noticed and wanted to note down before forgetting.

**Comment by danloh** [comment]
Thanks

**Comment by danloh** [comment]
maybe due to `state management`

**Comment by johnblommers** [comment]
There seems to be a big performance optimization opportunity here.

I just found `mdSilo` and had it open a directory with 176 Markdown files in it. They take 9.6 Megabytes of storage. They refer to a directory of 605 images totaling 105 MBytes. Hours later `WebKitWebProcess` is spinning two cores and hogging 9.6 GBytes of RAM. The GUI isn't responsive. The app is unusable.

My sense is that mdSilo has need for some serious optimization. Until then it's good for small projects.

But oh! the potential mdSilo has.

**Comment by danloh** [comment]
> In my case the hanging up of mdSilo was due to the presence of other directories containing DOCX, PDF et. al. files. By all indications I think mdSilo is looking at files it has no idea about and hanging up. IMHO it should restrict itself to examining Markdown files.

Thanks for your hint

**Comment by danloh** [comment]
Improved on v0.5.6
