### ISSUE TITLE
[Feature Request] Note Versioning

### ISSUE THREAD

**Issue by 8ullyMaguire** [mdSilo/mdSilo-app#540]
I think it would be extremely useful to have version control and history tracking on notes. That way users could look back at previous iterations of a note to view changes over time.

Some ways note versioning could work:
* Auto-save note revisions either periodically or on major edits
* Allow viewing note history with a timeline of all revisions
* Restore previous versions of a note
* Compare changes between any two revisions
* Optional version comment summarizing changes

This would help users track their thought process on a note topic over time. It provides insurance against unintended changes or content loss.

The version history could be displayed visually with a timeline and comparison view. Or kept simple with just the ability to restore previous revisions.

Either way, having the ability to see past versions of a note and roll back unwanted changes would be invaluable. It gives users confidence that their work is safe. Please consider adding note versioning capabilities to further enhance the knowledge management features.

edit: as an alternative there's always git. It could be left to a plugin to commit changes with git every x minutes.

**Comment by danloh** [comment]
Thanks for the idea. I will think of this. 

And the current stopgap is using GitHub or other similar services to sync the local notes.
